### ISSUE TITLE
Unable to import as a .csv

### ISSUE THREAD

**Issue by ahaverty** [jcalazan/glucose-tracker#20]
Hi Jonathan,
I'm having trouble uploading a csv file. I can't get past the error "File type (application/vnd.ms-excel) is not supported." even when uploading blank .csv files.

![csv issue](https://cloud.githubusercontent.com/assets/2920947/7434535/5be85c28-f033-11e4-968b-90d71be210c4.PNG)

Also, I attempted to upload a .txt file and was given a server error:
![server error](https://cloud.githubusercontent.com/assets/2920947/7434547/7cfcc75a-f033-11e4-8193-9c0303f84e59.PNG)

Best of luck with this project!

**Comment by jcalazan** [comment]
Hey Alan,

Thanks for reporting this!

Do you mind sending the file(s) you  were trying to upload to info@glucosetracker.net?  Server log is showing something about a 'NULL byte', my guess is the file has binary content.

**Comment by ahaverty** [comment]
Hi Jonathan,
I forgot to add, when I download your template csv and try to import that unedited, I get the same file type error as above. 
I can send you what I was planning to import. Thanks!

**Comment by ahaverty** [comment]
Sent bg readings csv in mail there. Cheers

**Comment by jcalazan** [comment]
Hey Alan,

Thanks for sending over the file.  I actually got a different error when uploading it, which was a bug (I wasn't handling mmol/L unit properly during import).  I just pushed a fix for that and your file now works for me in Chrome and Firefox.

Do you mind giving it another shot?  If you're still getting the same error, can you tell me which browser you are using?

Thanks!

**Comment by ahaverty** [comment]
Hi Jonathan,
Logged out, logged back in and tried uploading the exact file I sent to you, still getting the file type error.
Firefox 37.0.2, I also tried in chrome awhile ago but was having the same issue.
Thanks!

**Comment by ahaverty** [comment]
Tried wiping the cache for your site too just incase, but same issue.

**Comment by jcalazan** [comment]
Ah interesting, must be a Windows thing.  I explicitly allowed that file type and pushed the changes, can you give it another shot?

Thanks!

**Comment by ahaverty** [comment]
Thanks Jonathan,
I'm now getting a file type error for application/binary for the same file and for when I download and try import the sample file provided.
![binary issue](https://cloud.githubusercontent.com/assets/2920947/7442255/99117624-f101-11e4-8840-e7eea3b56402.PNG)

**Comment by jcalazan** [comment]
Wow, that's weird.  I added that content type just now, let's give it one more shot!

**Comment by ahaverty** [comment]
That worked, thanks for your time Jonathan!
